spring:
  datasource:
    url: jdbc:h2:mem:awesomepizza;Mode=MySQL
    #url: jdbc:h2:file:/data/awesomepizza;DB_CLOSE_DELAY=-1;AUTO_RECONNECT=TRUE;MODE=MySQL;
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
springdoc:
   api-docs:
      path: /api-docs
server:
   port: 8083
